[workspace]
members = [
  "microbot",
  "test-utils",
  "tests"
]
resolver = "2"

[workspace.dependencies]
futures = "0.3.33"
http = "1.5.0"
matrix-sdk = { version = "0.18.0", default-features = false }
regex = "1.13.1"
ruma = { version = "0.17", features = ["events"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.19"
tokio = "1.53.1"
tracing = "0.1.44"
