name: Fmt

on:
  push:

jobs:
  check_fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: |
          rustup toolchain install
      - run: |
          cargo fmt -- --check
