name: Fmt

on:
  push:

jobs:
  check_fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - run: |
          rustup toolchain install
      - run: |
          cargo fmt -- --check
