name: license-check

on:
  push:

jobs:
  license:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
    - name: Check License Header
      uses: apache/skywalking-eyes/header@55373684d1b70e5f8fd9fc8ec114a89ad11a56a3
