name: Machete

on:
  push:

jobs:
  machete:
    name: cargo machete
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: |
          rustup toolchain install
      - run: |
          cargo install cargo-machete --locked
      - run: |
          cargo machete
