name: Test

on:
  push:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - run: |
            rustup toolchain install

      - uses: michaelkaye/setup-matrix-synapse@e080023c56271cab986b83db75edba570fafb88b # main
        with:
          uploadLogs: true
          httpPort: 8008
          disableRateLimiting: true
          customConfig: |
            {
              "enable_registration_without_verification": true,
              "enable_registration": true
            }

      - run: cargo test
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: info,micro=trace,matrix=trace,ruma=trace,test=trace
